zalando-stups/senza

senza/cli.py

This allows direct reference to an existing IAM role

Added simple IAM instance profile support

---

senza/traffic.py

Don't show exception and raise UsageError when trying to change traffic for stack without domain

Human friendly error when using traffic with stack without domain

---

senza/templates/postgresapp.py

The ports for postgres (5432) and healthcheck(8008) are injected into the variables for the Postgres Appliance

Postgres Appliance template: Correct injection of ports.

---

senza/templates/postgresapp.py

The Load Balancer is created to route traffic to the current master. It is using a health check provided by Governor to determine the status of the master.
A CNAME DNS record is created for the load balancer.
To determine the Hosted Zone we currently ask the user to provide it during senza init.

Spilo: Add Load Balancer and nice DNS name for the PostgreSQL appliance.

---

senza/templates/postgresapp.py

The Securtity Group was not resolved correctly, therefore we use a function to determine the group id from now on.
The defaults for hosted zone and etcd appliance are now taken from the default_zone; this makes the init process requiring less input from the user.

Senza postgresapp template: Sanitize senza init process.

---

senza/templates/postgresapp.py

To be able to use the latest Taupage (with berry), we need to specify a mint bucket.
We refactored pg_master into master.

Spilo template: Add mint bucket and refactoring.

---

senza/components.py
senza/templates/postgresapp.py

Add an ability to configure filesystem type, options, provisioned IO requests for the IO1 EBS volumes, as well as optional scalyr account credentials. In addition, allow EbsOptimized flag in the senza autoscaling group template and use it always for PostgreSQL instances.
Trim extra long lines in postgres template.

Additional configuration options for the postgres template

---

senza/templates/postgresapp.py

- Allow S3 access for read to mint bucket
- Allow full S3 access for WAL-E bucket
- Allow setting tags on EC2 objects
- Allow browsing EC2 objects
The latter 2 actions doesn't seem to support specific
resources, so we set it for *.

Fine-grained permissions for spilo app.

---

senza/templates/bgapp.py
senza/templates/postgresapp.py

I want to be able to use senza without zalando-style accounts/vpc's. With AssociatePublicIpAddress as a default value one is able to see what to change in the yml file to do so.

add AssociatePublicIpAddress as a parameter for all stack types

---

senza/cli.py
tests/test_cli.py

senza was missing the support for mustache in templates
ValueError: Security Group "app-{{Arguments.ApplicationId}}" does not exist

add mustache-support for Template-Parameters/Arguments

---

senza/templates/postgresapp.py

This is needed for automatic start of etcd proxy by taupage.
Plus rename environment variable ETCD_DISCOVERY_URL to
ETCD_DISCOVERY_DOMAIN (just to be consistent with taupage)

Set etcd_discovery_domain in a TaupageConfig

---

senza/components.py
tests/test_components.py

Previously it was always `HTTP`.

Added support for other protocols for load balancer health check.

---

senza/templates/postgresapp.py

As spilo resides in the open-source registry, we can
autodetect the latest image and put it into the generated
template. Alternatively, we allow a user to stick with the
previous behavior of specifying an image during create.
When getting the latest image, the logic is to fetch the
latest non-snapshot one before trying with snapshots.

Allow spilo  docker image to be specified at init.

---

senza/templates/postgresapp.py

The whole description is retuned and not just the tag name, and also the last seen tag is taken instead of the latest one.

Fix an issue when detecting the latest tag

---

senza/cli.py
tests/test_cli.py

Positional and keyword parameters can be used together, much like
in Python.  A positional parameter must not follow one specified
with a keyword.
This also checks that no parameters is specified more than once
(either as positional or keyword) and that every parameter is
assigned a value.  Adding default parameter values should be easy
with this in place.

Handle keyword parameters in create and print cmds

---

senza/cli.py

It is useful then adding new instances to the cluster that are using a different docker image version rather than the already running instances, which is going to happen more as people try minor version upgrades, bugfixes, etc. especially with DB-like appliances.

Add --docker-image param to instances command

---

senza/cli.py
tests/test_cli.py

CloudFormation templates were being created with `DefaultValue` instead of `Default` resulting in
{"Error":{"Code":"ValidationError","Message":"Invalid template parameter property 'DefaultValue'","Type":"Sender"},"RequestId":"..."}
I don't think anyone was using the DefaultValue feature or they would be getting the same CF errors. For this reason the quickest and easiest fix is just to rename the Senza syntax to use `Default`.

Fixed default parameter values

---

senza/templates/postgresapp.py

Some usage of Spilo does not keep the connection alive, for example interactively querying using psql.
The default timeout of 60 seconds is not adequate for these usecases.
Fixes some occurces of https://github.com/zalando/spilo/issues/25

Increase the timeout for ELB's serving Spilo.

---

senza/aws.py

Providing `None` as filter results in exception:
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter StackStatusFilter, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
```

Fix crashing "senza list --all"

---

senza/components/taupage_auto_scaling_group.py
tests/test_cli.py
tests/test_components.py

This PR solves the issue #46
It allows to put any valid Fn::* in UserData and Ref in the TaupageConfig property of a Senza::TaupageAutoScalingGroup.
Something like that:
```yaml
SenzaComponents:
- Exhibitor:
Type: Senza::TaupageAutoScalingGroup
TaupageConfig:
environment:
S3_BUCKET: {Ref: "ExhibitorBucket"}
S3_PREFIX: "exhibitor"
Resources:
ExhibitorBucket:
Type: AWS::S3::Bucket
```
will expand into:
```json
{"UserData": {"Fn::Base64": {"Fn::Join": ["", [
"#taupage-ami-config\nenvironment:\n  S3_BUCKET: ",
{"Ref": "ExhibitorBucket"},
"\n  S3_PREFIX: exhibitor\n"]]}}}
```
It first transforms the configuration tree so the nodes representing *Ref* or *Fn::* are transformed into a template string such as *{{ json }}*, where *json* is the JSON representation of the AWS function.
Then it is …

Allow AWS functions and Ref in TaupageConfig

---

senza/components/elastic_load_balancer.py

Set connection draining to 60s by default (can be overwritten in Senza definition!)

#140 enable ELB connection draining by default (60s)

---

senza/traffic.py
tests/test_cli.py

`traffic.inform_sns` was receiving a `region` but not using it for anything. This caused the error seen in zalando/lizzy#24.

Use region in traffic.inform_sns

---

senza/aws.py
tests/test_aws.py

get_security_group() uses the option '--group-names'
But this option only works for the default VPC. See here:
http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html
--group-names
[EC2-Classic and default VPC only] One or more security group names. You can specify either the security group name or the security group ID. For security groups in a nondefault VPC, use the group-name filter to describe security groups by name.
This pull request replaces the option group-names by a group-name filter

Fixing get_security_group() when running it in a non-default VPC.

---

senza/aws.py
senza/templates/postgresapp.py
tests/test_aws.py
tests/test_cli.py

Some features of the Postgresapp (Spilo) template implicitly relied upon region being set in the account_info.
It should in fact have relied upon the region explicitly specified.
Fixes https://github.com/zalando/spilo/issues/44

Bugfix: Make region dependent calls explicit

---

senza/components/auto_scaling_group.py
tests/test_components.py

Fixes #177
This PR make the following properties configurable for an AutoscalingGroup:
* Period
* EvaluationPeriods
* Statistic
* Cooldown
* ScalingAdjustment

#177 configurable autoscaling properties

---

senza/templates/postgresapp.py

Spilo members currently do not allow connections on port 9100.

Allow ZMON to access Promotheus Node Exporter

---

senza/cli.py

While using `senza` I got a error message with a small typo. Just fixing it here.

Fix small typo

---

senza/aws.py
senza/components/auto_scaling_group.py
tests/test_aws.py
tests/test_cli.py

Cross-Stack references to EC2 security groups and IAM Roles are resolved
using the cloudformation API. Resources are referenced by the full stack
name and the resource's logical identifier.
Resources:
HelloWorldRole:
Type: AWS::IAM::Role
- AppServer:
Type: Senza::TaupageAutoScalingGroup
IamRoles:
- Stack: a
LogicalId: HelloWorldRole
References #151 - will provide an example on how this can 'fix' the issue.

Allow cross-stack-references to SGs and Roles

---

senza/templates/postgresapp.py

since t2.micro is too small to even load the docker image.

Set the default Spilo instance type to t2.medium

---

senza/templates/__init__.py

- avoid crashing on a module without the description
- make sure a template to plug is always a module (i.e. not a function).

Fix minor issues with pluggable templates.

---

senza/cli.py

Fixes #221 
For some reason the `dns.resolver.query(name, 'CNAME')[0].target.to_text()` returns a `bytes` string instead of `str` causing the error described in the issue. This PR guarantees that the response is a `str` instance so we can call `.startswith` with proper types.

Guarantee .to_text response to be str

---

requirements.txt
senza/components/taupage_auto_scaling_group.py
tests/test_components.py

Fixes #223
Depends on https://github.com/zalando-stups/pierone-cli/pull/38

Warn about insecure images

---

senza/cli.py
tests/test_cli.py

This pull request would allow reading parameters from file.
Kind of what was suggested in issue #100 
The benefit would be that you could have environment specific arguments in files like..
senza create --parameter-file **ci**.yaml your-senza.yaml 1 1
senza create --parameter-file **prod**.yaml your-senza.yaml 1 1
It should work like before, so if you are missing parameter from file, that is defined senza.yaml, you need to give it from cli
senza create --parameter-file **prod**.yaml your-senza.yaml 1 1 MissingParam=TheParam

Possibility to read parameters from file

---

senza/error_handling.py
tests/test_cli.py
tests/test_error_handling.py

it is now handled the same as a NoCredentialsError Exception.
ClientError with code AccessDenied can happen when switching to another AWS role
(with ``aws sts assume-role --role-arn...`` for example).
If the token returned from that command expired, we get an accessdenied.
Small refactor to avoid code duplication.

Handle ClientError with code AccessDenied

---

senza/components/elastic_load_balancer.py

Fixes #182 
The warning was there since February.

Remove NameSufix Typo in elastic_load_balancer.py

---

senza/manaus/elb.py

Fixes #293 (internal ELBs cannot be used).
Some ELB properties might not be present.

#293 SSLCertificateId and CanonicalHostedZoneName might not be set

---

senza/templates/postgresapp.py

To address issue #299, we should only encrypt non-empty
variables.

Ensure variables are not empty when encrypting

---

senza/components/stups_auto_configuration.py
tests/test_components.py

Fixes #37 by allowing to set the VpcId in the Senza definition thus allowing multiple VPCs and selecting the right one manually.

#37 allow setting the VpcId for StupsAutoConfiguration

---

senza/cli.py
senza/utils.py

Fixes #308
Problem was that generators are truthy so when stack were not found Senza was getting in an infinite loop.

Fix infinite loop calling AWS API when using senza wait

---

senza/cli.py
senza/error_handling.py
senza/manaus/cloudformation.py
senza/manaus/exceptions.py
senza/traffic.py
tests/test_cli.py
tests/test_error_handling.py
tests/test_manaus/test_cloudformation.py

Fixes #184 
Fixes #194
The old logic will still be applied to records that don't belong to a stack to avoid breaking something that's working.

Change traffic by updating the stack.

---

senza/templates/postgresapp.py

In Patroni 1.0 a change of the configuration was introduced.
This change ensures newly created Spilo's default to Patroni 1.0
valid configuration.
Addresses https://github.com/zalando/spilo/issues/83

Update Patroni config section to >= Patroni 1.0

---

senza/components/auto_scaling_group.py
tests/test_components.py

Now it is possible to specify custom tags in the autoscaling group declaration, like this:
```
- ClusterInstance:
Type: Senza::TaupageAutoScalingGroup
Tags:
-  Key: MyEnvironment
Value: staging
AutoScaling:
....
```
This function is especially useful when you need to select a particular AutoScaleGroup entity in ZMON.

Add support for custom tags for both AutoScalingGroup and TaupageAutoScalingGroup

---

senza/traffic.py
tests/test_cli.py

#321: fallback to direct manipulation if CloudFormation says "no update needed".
This is important for a seamless migration to the new Senza version (otherwise old versions (manipulated with old Senza) will still get DNS traffic!),

#321 fallback to direct DNS upsert if CF is not updated

---

senza/components/elastic_load_balancer.py
senza/components/elastic_load_balancer_v2.py
senza/components/weighted_dns_elastic_load_balancer.py
senza/components/weighted_dns_elastic_load_balancer_v2.py
tests/test_components.py

#310: Further steps towards full ELBv2 support
* remove duplicate code
* allow overwriting ELBv2 / target group properties
* default health check path is now '/health' (much more reasonable, "/ui/" was just convenient for original STUPS microservices)

#310 code cleanup and allow overwritting ELBv2 properties

---

senza/error_handling.py
tests/test_error_handling.py

When getting the error: access_denied_error (which means: credentials are present in .aws/credentials or in env variables, but the associated user does not have proper access rights on the AWS resource),
Senza reported:
No AWS credentials found. Use the "mai" command-line tool to get a temporary access key
or manually configure either ~/.aws/credentials or WS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY.
Which is not correct: the credentials ARE present. That cost me a bit of time to find the issue.
Also,
- DRY up the code: do not repeat exit(1) all the time.
- Display errors using the clickclick.fatal_error function, which colors the error in red all the time.

Fix bad message credential access error

---

senza/manaus/ec2.py
tests/test_manaus/test_ec2.py

Don't assume VPCs have tags

---

senza/arguments.py
senza/cli.py
tests/fixtures.py
tests/test_cli.py

Use [`boto3.session.Session.get_available_regions('cloudformation')`](http://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.get_available_regions) to get all valid AWS regions.

Validate region against a list provided by boto3

---

senza/aws.py
senza/cli.py
senza/manaus/acm.py
senza/manaus/boto_proxy.py
senza/manaus/cloudformation.py
senza/manaus/ec2.py
senza/manaus/elb.py
senza/manaus/iam.py
senza/manaus/route53.py
senza/patch.py
senza/respawn.py
senza/templates/_helper.py
senza/templates/postgresapp.py
senza/traffic.py
tests/test_manaus/test_boto_proxy.py

Fixes #137
`BotoClientProxy` replaces `boto3.client` and works by passing every call to an internal instance of `boto3.client` but retrying the call if it gets a throttling exception.

Boto.client proxy to retry on throttling

---

tests/test_subcommands/test_root.py

The test was failing when running in a path outside `/home`.

make test directory independent

---

senza/error_handling.py
senza/manaus/exceptions.py

- Docstrings;
- More specific variable names;
- Reduced some code repetition;
There are still a couple of warnings because `sentry` is constant but lower case, the catch-all except and the typing imports.

Improve senza/error_handling.py based on pylint

---

senza/utils.py
tests/test_utils.py

- Docstrings;
- Argument name changed in `named_value` (still not really better);
- Removed one step from `camel_case_to_underscore` (@hjacobs I couldn't find any case that failed without it but maybe I'm missing something can you check this change?)

Improve senza/utils.py based on pylint

---

senza/traffic.py
tests/test_traffic.py

I'm singling out this import since it's the only import error I saw on Sentry and there are already multiple reports from multiple hosts.

Show helpful error if dns.resolver import fails

---

senza/components/stups_auto_configuration.py
senza/components/subnet_auto_configuration.py
tests/test_components.py

For our Kubernetes setup: allow configuring public subnets without Taupage

add SubnetAutoConfiguration component with PublicOnly option

---

requirements.txt

dnspython3 has been superseded by the regular dnspython kit, which now supports both Python 2 and Python 3.

use dnspython instead of deprecated dnspython3

---

requirements.txt
senza/aws.py

As the test was failing on my machine I think our function was not robust enough, so it's a good idea not to reinvent the wheel and use a well tested module for parsing the date.

Use Arrow to parse datetimes

---

senza/error_handling.py

As `mai` was deprecated `senza` shouldn't suggest it's use.

Replace reference to mai with zaws

---

senza/error_handling.py
senza/exceptions.py
senza/patch.py
tests/test_patch.py

Prevent senza patch from destroying user data

---

senza/components/elastic_load_balancer_v2.py

I added one additional line for supporting http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes in ELBv2

Support for additional properties, eg. IdleTimeout of load balancer

---

senza/aws.py

This copies the logic from manaus/cloudformation: https://github.com/zalando-stups/senza/blob/master/senza/manaus/cloudformation.py#L199

do not fail if no updates are to be performed

---

senza/components/taupage_auto_scaling_group.py
tests/test_components.py

Instead of throwing an error if the existing token expires, now we try to re-login and return the token.

#441 Try to log into Pier One if the existing token has expired.

---

senza/aws.py
senza/cli.py
senza/traffic.py
tests/test_cli.py

Related to https://github.com/zalando/lizzy/issues/194
Only waits stacks to be ready if specified the timeout period. By default behaves the same way as before, trying to exectute the traffic change immediately.

Only waits for traffic change if timeout provided

---

senza/manaus/cloudformation.py

Fixes #456 
Capabilities parameter is optional for certain types of CF stack, but does not accept `None` as value.
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html

Capabilities parameter does not accept None as value

---

senza/cli.py
senza/components/elastic_load_balancer.py
senza/utils.py
tests/test_utils.py

Currently when getting stack health through `senza health` the LB metrics cannot be fetched for stacks with long application names. This is because the application name is truncated when creating the load balancer. However in the `health` command the name truncation is not performed which means the metrics are not fetched correctly. This PR moves the truncation function to the `utils` package so that it can be used in the `cli` module as well as the `elb` module.

Refactored get_load_balancer_name to be used when getting stack health

---

senza/cli.py
tests/test_cli.py

Right now `senza list` returns a fixed list of fields for each stack. There're use cases where I might only need some of them, e.g. `version`.
I'm proposing to add `--field` option which would allow to specify which field to include in the output:
```bash
$ senza list -o tsv my-stack --field version
version
1
```
It's possible to specify parameter multiple times in the command line if more parameters needed:
```bash
$ senza list -o tsv my-stack --field version --field stack_name
stack_name      version
my-stack        1
```
If no `--field` parameter specified, the tool will output all fields as before:
```bash
$ senza list -o tsv my-stack
stack_name      version status  creation_time   description
my-stack        1       UPDATE_COMPLETE 7h ago  My Stack
```

Allow filtering of fields returned by senza list

---

senza/components/elastic_load_balancer.py
senza/components/elastic_load_balancer_v2.py
senza/utils.py
tests/test_components.py
tests/test_utils.py

Issue Number: #467
The old ELB Configuration has a Property "LoadBalancerName", the new ALB Configuration not. If we support this property in ALB, user can switch from ELB to ALB and will have the same LoadBalancerName.

Check if LoadBalancerName is set

---

senza/cli.py
senza/error_handling.py
senza/exceptions.py

If a parameter file is empty senza will currently raise the following exception:
```
AttributeError: 'NoneType' object has no attribute 'items'
```

Proper error if parameter file is empty

---

senza/traffic.py
tests/test_traffic.py

The import error handling is no longer needed (the use case was the migration from dnspython3 to dnspython).
This fixes the failing unit test.

remove dns.resolver import error handling

---

.zappr.yaml

The only org allowed in zappr.yaml is zalando.

Fix zappr yaml

---

senza/traffic.py

The PR which introduced the changed handling of set traffic solving the UPDATE_IN_PROGRESS issue with stacks having multiple ELBs (and therefore multiple DNS names) did treat a `stack` object returned by `CloudFormationStack.get_by_stack_name` as if it would be the same object being returned by subsequent calls with the same stack_name. As this is not the case this leads to only the first update being actually executed.

Fix issue with changed set traffic handling

---

senza/components/elastic_load_balancer.py
tests/test_components.py

HTTP and HTTPS have `HTTP(S):<port><path>` target syntax but TCP does not know about paths: `TCP:<port>`.
See here:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-health-check.html#cfn-elb-healthcheck-target

Fix TCP mode for the ELB component by using a correct health check

---

senza/cli.py
tests/test_cli.py

#478 fixed. 
* User should confirm operation when more than one stack found to scale. 
* `--force` flag used to turn off confirmation and scale all found instances.

#478 - 'senza scale' prompt when more than one instance might be scaled.

---

senza/components/subnet_auto_configuration.py

NAT gateways created by https://github.com/szuecs/kube-static-egress-controller/ will also get a new subnet, because servers could be placed in dmz or private subnets and both has to be routed for given static egress targets.
Senza will normally find these NAT subnets and place ELB interfaces into them, which create failures at runtime.

fix senza not to put NAT subnets into server subnets

---

senza/cli.py
tests/test_error_handling.py

`yaml.load` allows executing arbitrary code, use `safe_load` instead.

yaml.load -> yaml.safe_load

---

senza/components/auto_scaling_group.py

There should be a way to disable InstanceMonitoring if its not needed for LaunchConfiguration

Disable InstanceMonitoring for LaunchConfiguration if needed

---

senza/components/taupage_auto_scaling_group.py
tests/test_components.py

Due to drop of pierone clair integration there's no more sense to keep the warnings during senza deployment (since pierone will reply with NOT_PROCESSED_YET for every image).
Basically this reverts #226

Cleanup of pierone CVE analysis

---

README.rst
senza/components/elastic_load_balancer.py
senza/components/elastic_load_balancer_v2.py
tests/test_components.py

- add support for multiple SSL certificates for ELBv2
- support both comma-separated string and list
Since ELBv2 supports SNI this commit will enable to put more than only one certificate in the Senza definition.

support multiple SSL certificates for ELBv2

---

senza/docker.py
tests/test_docker.py

We want to drop v1 support from Pier One, senza is one of the remaining users of it.

Use Pier One v2 API to check if image exists

---

.travis.yml
examples/elastigroup.yaml
requirements.txt
senza/cli.py
setup.py
spotinst/__init__.py
spotinst/components/elastigroup.py
tests/test_elastigroup.py

This change tries to simplify the definition of Elastgroups by assuming some defaults like the native Auto Scaling Group counterpart.
It also adds support for the automatic subnet mapping from `Senza::StupsAutoConfiguration`
It assumes, for now, that the cloud accounts provisioned in Spotinst will be named "aws:<aws-account-id>". This is used for Spotinst cloud account resolution and it's needed to use a specific account instead of the default one.
/cc @danieldop @jmcs

Extend spotinst elastigroup

---

spotinst/components/elastigroup.py
tests/test_elastigroup.py

Also made the fallback to on demand always true, as per [Spotinst's recommendations](https://github.com/zalando-stups/senza/pull/516#pullrequestreview-136726224).
Closes #520 
/cc @jmcs @talzur

InstanceType mandatory for elastigroups

---

spotinst/components/elastigroup.py
tests/test_elastigroup.py

Spotinst changed the API to support backend [matching for a given AWS account ID](https://api.spotinst.com/organization-accounts/get-accounts/)
This change makes the cloud account resolution more efficient and less fragile (no longer parsing the cloud account name).
This should also enable users to keep more user-friendly names in the Spotinst cloud accounts.

refactored Spotinst cloud account matching

---

delivery.yaml

This will avoid triggering dependent pipelines by mistake.

Create a different image for PRs

---

senza/components/elastigroup.py
tests/test_elastigroup.py

This shouldn't cause any surprises since the previous behavior was "mostly" to keep the explicit resource names.
It closes #534 
/cc @pc-alves @jmcs

removed Config suffix from Elastigroup resource names

---

senza/components/elastigroup.py
tests/test_elastigroup.py

The native AutoScalingGroup allowed a [subset of CloudFormation properties to be set directly](https://github.com/zalando-stups/senza/blob/98bcf0fe68cba1193d72744ba30d4f86445c261d/senza/components/auto_scaling_group.py#L17)
Some of the keys don't make sense/are not usable with Elastigroups: `TerminationPolicies` and `MetricsCollection`.
The `PlacementGroup` is supported by the Elastigroup and should be addressed separately.
This change adds support for the `TargetGroupARNs` property. When present, they will be set as the [Elastigroup's `loadBalancers`](https://api.spotinst.com/spotinst-api/elastigroup/amazon-web-services/create/).
The [default TargetGroup is still created by the `ElasticLoadBalancerV2` component](https://github.com/zalando-stups/senza/blob/98bcf0fe68cba1193d72744ba30d4f864 …

added support for the TargetGroupARNs property in Elastigroups

---

senza/components/auto_scaling_group.py
tests/test_components.py

When the `SuccessRequires` is 0 of int type, the check does not as expected, and returns `"1"` for the CloudFormation. When the `"0"` of str type is used, it works fine. Because `if 0` is false, while `if "0"` is true.
As a result, the formations with 0 expected instances in start fail to create when in the AWS, because it expects at least 1:
```
AutoScaling:
Minimum: 0
Maximum: 1
DesiredCapacity: 0
SuccessRequires: 0     # <== fails
SuccessRequires: "0"   # <== works
```
This fix makes the check more specific, and the only assumed "absent" value could be `None` here (despite this case is not mentioned in the tests at all, and not present anywhere in the code).
Therefore, the `0` int value goes to the actual check for `int` type, and is now handled properly.

Fix zero instances for SuccessRequires in AutoScalingGroups

---

examples/elastigroup.yaml
senza/cli.py
senza/components/elastigroup.py
senza/spotinst/components/elastigroup_api.py
tests/test_cli.py
tests/test_elastigroup_api.py

This should fix the problem to use the auxiliary commands scale, patch and respawn
It stopped working with #535 and would fail if the Elastigroup component name was not `AppServer`

Fix spotinst stack details

---

tests/test_cli.py

In Travis this test contains an upper case `DEFINITION`. CDP builds have a lower case `definition`.
The case should not be relevant to the semantics of the test.

trying to fix flaky test_invalid_definition

---

senza/components/elastigroup.py
senza/patch.py
tests/test_elastigroup.py
tests/test_patch.py

The function `base64.urlsafe_b64encode()` would fail to properly encode the `>` character, as stated in #540 
That affected the Elastigroup creation whenever the `>` was present in the user data.
For the CloudFormation template the fix was to use the same deferred call to `Fn::Base64`, just [like for the native Auto Scaling Groups](https://github.com/zalando-stups/senza/blob/0b7c7cee8d7c4f1a2bc01c9cc2cad42171292d98/senza/components/taupage_auto_scaling_group.py#L144).
The patch command was changed to use the correct `base64.b64encode()` function.

fixed the user data encoding by using the proper base64

---

senza/aws.py
senza/cli.py
senza/components/auto_scaling_group.py
senza/components/elastic_load_balancer.py
senza/manaus/acm.py
senza/manaus/cloudformation.py
senza/manaus/elb.py
senza/manaus/exceptions.py
senza/manaus/iam.py
senza/manaus/route53.py
senza/respawn.py
senza/subcommands/root.py
senza/templates/__init__.py
senza/templates/_helper.py
senza/traffic.py

The newest release of flake8 is stricter than previous ones, so the master build was broken.
This PR fixes it by:
- Formatting affected files with black;
- Removing an unused assignment.

Fix flake8 checks

---

senza/cli.py
tests/test_cli.py

This small change seems to be enough to allow reporting instances managed by Elastigroups.
Only AWS can set `aws:` prefixed tags. Instances created by the Elastigroups don't have the `aws:cloudformation:stack-name` tag that was used to filter instances.
Pragmatically, I believe that the `Name` tag contains exactly the same information, although the guarantee that it was created by CloudFormation no longer exists.
If this new approach doesn't sound reasonable, please share the particular uses cases or assumptions where this change will break.
This also changed the instance state filtering to the server side for some micro optimization.
This updates #517

change in the strategy to report instances

---

senza/components/elastigroup.py
tests/test_elastigroup.py

This PR makes changes to the way standard STUPS tags specified within `ElastiGroup` component are handled:
* Standard tags are always added to the list of tags even in the presence of custom tags
* Any standard tags specified in configuration are overridden by values from Senza definition - I have never ever had to specify these tags manually, so please let me know if you think there's a valid use case when it might be useful to actually override tags and I will change the logic

Always add standard STUPS EC2 tags

---

tests/test_components.py

see https://github.com/zalando-stups/pierone-cli/pull/78 
there is no `get_image_tag` in api.py after above PR. 
Switched to get_latest_tag that does almost the same.

docker image tags tests fixes

---

senza/components/elastic_load_balancer.py
senza/components/elastigroup.py
senza/manaus/iam.py
senza/templates/_helper.py
senza/utils.py
tests/test_elastigroup.py
tests/test_manaus/test_acm.py
tests/test_manaus/test_iam.py
tests/test_templates.py

On March 18, 2019, AWS introduced limitations to the scope of calls to stack level APIs, such as DescribeStackResources. These APIs are used by aws-cfn-bootstrap scripts, including cfn-init and cfn-hup, which are commonly used to provision EC2 instances created by CloudFormation.
This limitation has not been applied to accounts that are making cross stack requests, but this will only be like that until May 30, 2019. When this comes into effect, it will prevent Elastigroup deployments from functioning as expected.
The policy added in this PR is the one recommended by Spotinst [in their documentation](https://api.spotinst.com/provisioning-ci-cd-sdk/provisioning-tools/cloudformation/cfn-helper/).
This policy will be added when running the `init` command and when creating new Elastigroup …

Add Cross Stack Policy to IAM Role

---

senza/components/elastigroup.py
tests/test_elastigroup.py

add discovery of other standard STUPS AMIs for Elastigroups

---

senza/cli.py
tests/test_cli.py

If the `MinSize` number of the autoscaling group was 0 and the user wants to scale up, we are overwriting `MinSize` with the new desired capacity. Users might not be aware of the fact that their stack might be downscaled after a time.

overwrite minSize instances if 0
