requirements.txt, senza/components.py, senza/templates/bgapp.py, senza/templates/webapp.py
application_version should use docker version instead of a stack version
=> fix application_version, using the docker image version

senza/aws.py, tests/test_aws.py
Ref. https://github.com/zalando-stups/senza/issues/63
=> Enable to recognize referenced Security Groups

senza/components/redis_cluster.py, senza/components/redis_node.py, tests/test_components.py
Add optional parameter CacheParameterGroupName to redis components
=> Add optional parameter CacheParameterGroupName to redis components

README.rst, senza/components/configuration.py, senza/components/elastic_load_balancer.py, senza/components/stups_auto_configuration.py
**As** a developer
**I want** to create ELBs with scheme 'internal'
**In order to** have ELBs which are only accessible from inside the VPN via their CNAME
=> Add support for configuration of load balancer scheme in Senza

senza/cli.py
This should add https://github.com/zalando-stups/senza/issues/99
Python3 urllib doesn't handle local files gracefully and the solution was to prefix file:// in the absence of '://'
=> Added support to load templates from http(s) endpoints

senza/components/elastic_load_balancer.py
Fix wrong ELB config when no scheme is defined in yam. Fixes #113
=> Fixes #113

senza/traffic.py, tests/test_cli.py, tests/test_traffic.py
This PR enables senza traffic to send SNS updates.
=> Add SNS notification on traffic update

senza/cli.py, senza/components/redis_cluster.py, senza/patch.py, senza/respawn.py, tests/test_cli.py, tests/test_patch.py, tests/test_respawn.py
Implementing #131: senza patch, senza scale and senza respawn-instances
No unit tests (yet).
=> Senza patch & respawn-instances

senza/components/auto_scaling_group.py
possible fix for #166, pls review.
=> #166 - create fails on ASG MinSize 0

senza/components/auto_scaling_group.py
We wanted to parametrize Minimum and Maximum values of AutoScaling
section to be able to specify them from command line and run into the
following problem:
```python
Generating Cloud Formation template.. EXCEPTION OCCURRED: unorderable types: int() > str()
Traceback (most recent call last):
File "/usr/local/bin/senza", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 1383, in main
handle_exceptions(cli)()
File "/usr/local/lib/python3.5/dist-packages/senza/cli.py", line 250, in wrapper
func()
File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File …
```
=> Explicitly cast value of Autoscaling Minimum and DesiredCapacity to integer

examples/network-scaling-policy.yaml, senza/components/auto_scaling_group.py, tests/test_components.py
Fixes #175
This PR introduces support for network scaling policies.
=> #175 support network scaling

senza/components/auto_scaling_group.py, tests/test_components.py
Fixes #180
This PR makes the CF stack's CreationPolicy configurable via `SuccessRequires: [required instances] within [timeout]`, e.g. `2 within 5m`. This is added to the `AutoScaling` property, see tests.
=> #180 configurable creation policy

senza/cli.py
Disclaimer: idk how to test this but hoping you get the idea ;)
=> Add {{AccountInfo.MintBucket}}

MAINTAINERS, senza/cli.py, tests/test_cli.py
=> Interactive delete

.gitignore, .travis.yml, tox.ini
Standardise the way of running the tests locally and in the CI.
=> Use tox for testing

senza/cli.py
=> Configurable wait interval

senza/aws.py, senza/cli.py
This mostly fixes #185 but we still need documentation after.
=> Regex based stack matching

senza/aws.py
This should fix the issue #216 
Version is set "" instead of None when version has no value.
=> Ensuring that version is a string as a fix for issue #216

senza/cli.py
Replace error message based on comment in #192. Makes it more clear to users what is going on.
=> Replace error message

senza/components/taupage_auto_scaling_group.py, tests/test_cli.py, tests/test_components.py
=> Validate application_id and application_version

senza/templates/_helper.py
=> Ask before creating IAM role

senza/cli.py, tests/test_cli.py
Fixes https://github.com/zalando-stups/senza/issues/233
=> Add validation of '--region' param

senza/cli.py, tests/test_cli.py
- when the instance is not found
- when the stack is not found
- when there are no instances in the region.
In those cases ``senza console`` just returned and displayed nothing, which was confusing for the user.
Add usage examples to ``console --help``.
Fix and add tests.
=> Add better output for the user to command 'console'.

senza/aws.py, senza/cli.py, tests/test_cli.py
=> Senza wait: support for re-using stack versions

senza/cli.py
=> Remove wrong argument on wait

senza/cli.py
Replace print by fatal_error on error in console()
=> Change sys error code to 1 on error in console()

senza/aws.py, senza/cli.py, tests/test_cli.py
=> Support UPDATE_COMPLETE in Wait

senza/components/elastic_load_balancer.py
=> Make the interface-facing ELB warning less conspicuous

senza/cli.py
=> Read named arguments from url

senza/error_handling.py
=> Improve error message when using unquoted Senza variables

senza/cli.py, tests/test_cli.py
After the refactor in https://github.com/zalando-stups/senza/pull/246,
the option for senza wait ``--delete`` is not needed anymore.
Small refactor (especially renaming ``stacks_nok`` to ``stacks_in_progress`` improves readability a lot, IMHO).
=> Add testcase to test_wait. Remove wait --delete

senza/cli.py
=> Ignore images without creation time

senza/cli.py, tests/test_cli.py
=> Fix senza wait for *_IN_PROGRESS

.coveragerc, senza/cli.py, senza/error_handling.py, senza/exceptions.py, senza/manaus/__init__.py, senza/manaus/route53.py, senza/stups/piu.py, setup.py, tests/test_error_handling.py, tests/test_manaus/test_route53.py, tests/test_stups/test_piu.py
=> Get odd host

senza/cli.py, tests/test_cli.py
=> Show error when stack is not found

senza/components/elastic_load_balancer.py, tests/test_components.py
=> #277 ignore SSLCertificateId if Listeners is overwritten (for HTTP only)

senza/components/auto_scaling_group.py, tests/test_components.py
fixes https://github.com/zalando-stups/senza/issues/273
=> make metrictype optional

senza/manaus/acm.py, tests/test_manaus/test_acm.py
=> #279 do not fail on ACM certs with status VALIDATION_TIMED_OUT

senza/components/elastic_load_balancer.py, senza/manaus/acm.py, tests/test_manaus/test_acm.py
=> Provide region to ACM

senza/cli.py, senza/manaus/route53.py
- Fix Main DNS in senza status;
- Delete dangling records when converting to Alias records;
=> Fix some issues caused by #275

senza/cli.py, senza/traffic.py, tests/test_cli.py, tests/test_traffic.py
=> Fix senza status for alias records

requirements.txt, senza/traffic.py, setup.py, tests/fixtures.py, tests/test_cli.py
=> Fix traffic change

senza/cli.py, tests/fixtures.py, tests/test_cli.py
Right now value shows up empty for Alias records
=> Fix senza domains value column for Alias Records

senza/error_handling.py, senza/manaus/exceptions.py, senza/manaus/route53.py, tests/test_manaus/test_route53.py
This method was initially done has part of #275 but ended up nothing being used. It can be useful in the future though.
=> Get record by name

senza/manaus/route53.py, tests/test_manaus/test_route53.py
=> Only call API for Route53 config if there is changes to be made

README.rst
This PR is part of an emerging effort to make Senza more newbie friendly.
=> Added "Why Senza" section to readme

senza/cli.py
This is just a first draft, but probably already useful :smile:
=> #88 add first draft of "senza health" showing ELB cloudwatch metrics

senza/cli.py, senza/stups/piu.py, tests/test_stups/test_piu.py
=> Don't connect to instances automatically if there's more than one

senza/components/auto_scaling_group.py, senza/components/elastic_load_balancer_v2.py, senza/components/weighted_dns_elastic_load_balancer_v2.py, tests/test_components.py
First draft of support for ELB v2 (#310).
=> Application load balancer

senza/components/auto_scaling_group.py, tests/test_components.py
=> allow overwriting ASG properties

senza/components/configuration.py, tests/test_components.py
=> #330 truncate default CF description to 1024 chars

senza/cli.py, senza/components/elastic_load_balancer_v2.py, tests/test_components.py
#310: more support for Application Load Balancer
=> ELBv2: support some metrics in senza health

senza/cli.py
#310: another step towards full ELBv2 support
=> ELBv2: show number of healthy instances

senza/components/elastic_load_balancer.py, tests/test_components.py
=> Internal default scheme

senza/cli.py, senza/error_handling.py, senza/exceptions.py, tests/test_cli.py
=> User friendly error when senza fails to parse the senza definition

senza/cli.py, senza/manaus/cloudformation.py, tests/fixtures.py, tests/test_cli.py, tests/test_manaus/test_cloudformation.py
Fixes #292 
Fixes #343 
I opted to require the force flag, since several users shown preference for this and it's consistent with deleting multiple stacks. After merging this the delete help of lizzy should also be changed to reflect this change.
=> Safe(r) delete

senza/cli.py, senza/exceptions.py, tests/test_cli.py
=> Better senza definiton error handling

senza/manaus/route53.py, tests/test_components.py, tests/test_manaus/test_route53.py
=> Add pagination to Route53.get_records

senza/aws.py
=> Fix file not found error

senza/components/elastic_load_balancer.py, senza/components/elastic_load_balancer_v2.py, senza/manaus/route53.py, senza/traffic.py, tests/test_manaus/test_route53.py
=> Only convert CNAME to alias

senza/manaus/utils.py, senza/traffic.py, tests/test_traffic.py
=> Make senza traffic work even when stacks are being deleted

senza/aws.py, senza/cli.py, senza/error_handling.py, senza/manaus/boto_proxy.py
Reduce code repetition by using extract_client_error_code everywhere senza needs the ClientError code
=> Use extract_client_error_code everywhere

senza/aws.py, senza/subcommands/root.py, tests/test_aws.py, tests/test_subcommands/test_root.py
=> Senza version check for TTY only

senza/aws.py, tests/test_aws.py
=> #357 lookup security group by tag "Name"

senza/manaus/elb.py, tests/test_manaus/test_elb.py
- Improve documentation
- Implemented pagination in `ELB.get_by_dns_name`
- Added missing property to `ELBListener`
=> Improve senza/manaus/elb.py based on pylint

senza/subcommands/root.py
- Added doctstrings
- Used specific variable names
- Formatting
- One sanity check that makes pylint happy
There's still one `exception-too-broad ` warning that was expected because we really want to ignore all exceptions and two errors related to https://github.com/PyCQA/pylint/issues/73
=> Improve senza/subcommand/root.py based on pylint

senza/respawn.py
- Docstrings;
- "Fix" some line breaks;
- Removed one unused variable from `do_respawn_auto_scaling_group`
2 warnings remain do the 2 TODOs.
=> Improve senza/respawn.py based on pylint

examples/autoscaling.yaml, senza/components/auto_scaling_group.py, tests/test_components.py
Basically #382, but with renaming.
=> Scale up down adjustment

senza/cli.py, senza/components/elastic_load_balancer.py, senza/components/elastic_load_balancer_v2.py, senza/definitions.py, tests/test_cli.py, tests/test_components.py
Done as part (but does not fix) #387.
This reduces clutter in cli.py.
=> Move AccountArguments to definitions module and document it

senza/components/elastic_load_balancer.py, tests/test_components.py
=> #370 resolve SSL certs when defining custom ELB Listeners

senza/subcommands/root.py, tests/test_subcommands/test_root.py
=> fix(messages): update error messages

senza/components/configuration.py, tests/test_components.py
Parameters might be too big...
=> allow skipping CF template parameter definitions

senza/components/weighted_dns_elastic_load_balancer.py, senza/definitions.py
=> Get hosted zone from route53 when creating template

senza/cli.py, tests/test_cli.py
=> Traffic change waits the stack to be ready

tests/test_cli.py
Less code and better readability.
=> Little refactor in traffic change tests

senza/components/coreos_auto_configuration.py, tests/test_components.py
=> #402 find latest AMI for CoreOS

senza/cli.py, senza/components/auto_scaling_group.py, senza/configuration.py, senza/error_handling.py, setup.py, tests/test_cli.py
=> Wait stacks to be ready before changing traffic

senza/aws.py, senza/error_handling.py, senza/exceptions.py, tests/test_error_handling.py
=> Suggest using senza init when SG doesn't exist

senza/aws.py, senza/components/auto_scaling_group.py, senza/definitions.py, senza/docker.py, senza/manaus/boto_proxy.py, senza/manaus/route53.py, senza/manaus/utils.py, senza/stups/piu.py, senza/templates/postgresapp.py, tests/test_aws.py, tests/test_docker.py
This pull request improves documentation, variable naming and removes one line of useless code
=> Pylint friday 2017 02

senza/aws.py, senza/cli.py, tests/test_cli.py
=> Add param --update-if-exists to senza create to make it idempotent

senza/error_handling.py
=> Suggest zaws instead of mai

senza/traffic.py
Fixes #453 
This pull request also removes two unused parameters in ``traffic.set_new_weights``
=> Don't try to change traffic unless really needed

.zappr.yaml
* complaint requires X-Zalando-Type
* putting `X-Zalando-Type` & `X-Zalando-Type` on top did avoid issues in the past
=> added X-Zalando-Type

senza/manaus/acm.py
=> Fallback to import time on ACMCertificate comparison

senza/components/taupage_auto_scaling_group.py
We have a use-case when we want to run instances in DMZ or public subnet but without public ips. Elastic ip would be assigned later to one of the instances.
Without public ip instance will not be able to initialize (download docker, push logs, use AWS api, etc...). To solve this problem taupage will create separate routing table for outgoing https requests and use a custom nat gateway for that.
=> Put nat_gateways into UserData if instance runs without public ip in DMZ

.travis.yml, tox.ini
Make sure setuptools are updated in travis build.
=> Fix tox builds

senza/cli.py
=> Drummerwolli empty params

senza/components/elastic_load_balancer.py
ref: #481 
update ALLOWED_HEALTH_CHECK_PROTOCOLS to add "HTTPS:443/status" format support for ElasticLoadBalancer Health check
=> update ALLOWED_HEALTH_CHECK_PROTOCOLS to add "HTTPS:443/status" format support for ElasticLoadBalancer Health check

.zappr.yaml
=> Reflect new team in zappr.yaml

senza/cli.py, senza/components/subnet_auto_configuration.py, senza/components/taupage_auto_scaling_group.py, senza/templates/_helper.py, senza/templates/postgresapp.py, senza/traffic.py, senza/utils.py, setup.py
Was breaking the build in GoCD
=> Fixed flake8 warnings

senza/cli.py
Fixes double "the": 'Updates the the stack if it exists'
=> Fix slightly incorrect doc in CLI

senza/components/stups_auto_configuration.py, senza/components/taupage_auto_scaling_group.py
`stups_auto_configuration`: fetch and configure `LatestTaupageStagingImage` and `LatestTaupageDevImage` as well.
=> Add support for multiple channels

examples/elastigroup.yaml, examples/elastigroup.yml, spotinst/__init__.py, spotinst/components/elastigroup.py
This PR fixes: https://github.com/zalando-stups/senza/issues/506
=> #504: Add Support for Spotinst Elastigroup Component

senza/cli.py, senza/error_handling.py, tests/test_cli.py
=> Senza kms decryption

requirements.txt, setup.py
Force an updated version of pytest to fix unit tests.
=> Update pytest version

spotinst/components/elastigroup.py, tests/test_elastigroup.py
This closes #519 
/cc @jmcs @talzur
=> fixed elastigroup healthchecktype

senza/traffic.py
Traffic switching was not working for stacks with multiple load balancers.The partial sum and count variables were incorect
=> #526 fixed calculation of partial count and sum

senza/spotinst/components/elastigroup_api.py
Highly opinionated timeouts. For a CLI tool, I believe these settings are ok.
This closes #542
=> Set Spotinst API timeouts

senza/components/elastigroup.py, tests/test_elastigroup.py
The behavior proposed now is to use the same Subnets that are being used with native Auto Scaling groups `LoadBalancerSubnets`.
The remaining options that control the actual network interfaces and the Elastic IPs were already working.
This just puts the network interfaces on the appropriate subnets.
This closes https://github.com/zalando-stups/senza/issues/543
=> fixed the public ips support for elastigroups

senza/cli.py
=> Fix type of batch_size_percentage option. Fixes #550.

senza/cli.py
This follows the same pragmatic approach as #547 
It updates #517
=> change in the strategy to report instance status

senza/components/elastigroup.py, tests/test_elastigroup.py
=> no longer poping the SpotinstAccessToken attribute

README.rst
Senza is not actively maintained anymore and users should consider migrating to a different tool.
=> Note about project status: not actively maintained anymore

senza/__init__.py
=> Increase version

senza/respawn.py
=> Break long lines
